version: '3.1'
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    restart: unless-stopped
    volumes:
      - .runtime/psql_data:/var/lib/postgresql/data
      - .runtime/root:/root
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdb

